CREATE TABLE places (
    
    id INT(7) NOT NULL AUTO_INCREMENT PRIMARY KEY
    name VARCHAR NOT NULL,
    location VARCHAR NOT NULL

);


CREATE TABLE people (
    
    id INT(7) NOT NULL AUTO_INCREMENT PRIMARY KEY
    name VARCHAR NOT NULL,
    location VARCHAR NOT NULL

);