/* Replace with your SQL commands */
CREATE TABLE products (
    id INT SERIAL PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE FLOAT NOT NULL,
    AVAILABLE BOOLEAN NOT NULL
);